# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package
on:
  release:
    types: [published]
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build package
      run: |
        make build

# ---- use this variant if you want to try out publishing to test.PyPi First
#    - name: Publish distribution 📦 to test.PyPI
#      uses: pypa/gh-action-pypi-publish@master
#      with:
#        repository_url: https://test.pypi.org/legacy/
#        user: __token__
#        password: ${{ secrets.TEST_PYPI_API_TOKEN }}

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
